let questions = [
    {
        numb: 1,
        question: "Qual é a principal fonte de poluição plástica nos oceanos?",
        answer: "Descarte inadequado de plásticos",
        options: [
            "Derramamento de petróleo",
            "Esgoto industrial",
            "Descarte inadequado de plásticos",
            "Fertilizantes agrícolas",
        ],
    },
    {
        numb: 2,
        question: "Qual tipo de poluição é causado principalmente pelo uso de fertilizantes e detergentes?",
        answer: "Eutrofização",
        options: [
            "Poluição térmica",
            "Eutrofização",
            "Acidificação",
            "Contaminação por metais pesados",
        ],
    },
    {
        numb: 3,
        question: "Qual é o impacto principal da poluição por microplásticos nos oceanos?",
        answer: "Ameaça à vida marinha",
        options: [
            "Alteração do clima global",
            "Destruição de corais",
            "Redução da biodiversidade em terra",
            "Ameaça à vida marinha",
        ],
    },
    {
        numb: 4,
        question: "Como a poluição por petróleo afeta os oceanos?",
        answer: "Contaminação da água e morte de organismos marinhos",
        options: [
            "Aumento da salinidade",
            "Redução da quantidade de oxigênio",
            "Contaminação da água e morte de organismos marinhos",
            "Destruição do ozônio",
        ],
    },
    {
        numb: 5,
        question: "O que é a acidificação dos oceanos?",
        answer: "Aumento da acidez da água do mar devido à absorção de CO2",
        options: [
            "Aumento da acidez da água do mar devido à absorção de CO2",
            "Redução da temperatura da água",
            "Acúmulo de poluentes químicos",
            "Derramamento de produtos químicos",
        ],
    },
    {
        numb: 6,
        question: "Qual é a principal causa da poluição térmica nos oceanos?",
        answer: "Despejo de água quente de usinas",
        options: [
            "Queima de combustíveis fósseis",
            "Descarte de plásticos",
            "Despejo de água quente de usinas",
            "Esgoto doméstico",
        ],
    },
    {
        numb: 7,
        question: "Qual é o efeito dos produtos químicos tóxicos nos oceanos?",
        answer: "Acúmulo em cadeias alimentares marinhas",
        options: [
            "Aumento da salinidade",
            "Acúmulo em cadeias alimentares marinhas",
            "Destruição de recifes de corais",
            "Alteração do clima",
        ],
    },
    {
        numb: 8,
        question: "O que são zonas mortas nos oceanos?",
        answer: "Áreas com baixos níveis de oxigênio onde a vida marinha não pode sobreviver",
        options: [
            "Áreas com baixos níveis de oxigênio onde a vida marinha não pode sobreviver",
            "Áreas de alta temperatura",
            "Áreas com alta concentração de plásticos",
            "Áreas afetadas por derramamento de petróleo",
        ],
    },
    {
        numb: 9,
        question: "Qual é uma das principais consequências da poluição por nutrientes?",
        answer: "Algas nocivas e mares revoltos",
        options: [
            "Redução da temperatura da água",
            "Aumento da biodiversidade",
            "Desaparecimento de micro-organismos",
            "Algas nocivas e mares revoltos",
        ],
    },
    {
        numb: 10,
        question: "Como os resíduos de pesca contribuem para a poluição dos oceanos?",
        answer: "Eles causam enredamento e morte de vida marinha",
        options: [
            "Eles causam enredamento e morte de vida marinha",
            "Alteram a salinidade da água",
            "Aumentam a acidez do oceano",
            "Reduzem a quantidade de nutrientes na água",
        ],
    },
    {
        numb: 11,
        question: "Qual é um dos efeitos da poluição sonora nos oceanos?",
        answer: "Perturbação na comunicação dos cetáceos",
        options: [
            "Perturbação na comunicação dos cetáceos",
            "Destruição dos recifes de corais",
            "Redução da quantidade de oxigênio na água",
            "Aumento da temperatura da água",
        ],
    },
    {
        numb: 12,
        question: "Qual é uma forma eficaz de reduzir a poluição plástica nos oceanos?",
        answer: "Reduzir o uso de plásticos descartáveis",
        options: [
            "Reduzir o uso de plásticos descartáveis",
            "Aumentar a produção de plásticos recicláveis",
            "Desenvolver novos tipos de plásticos",
            "Queimar plásticos em alta temperatura",
        ],
    },
    {
        numb: 13,
        question: "Qual é o impacto da poluição por metais pesados nos oceanos?",
        answer: "Contaminação da cadeia alimentar marinha",
        options: [
            "Contaminação da cadeia alimentar marinha",
            "Aumento da temperatura da água",
            "Destruição dos recifes de corais",
            "Redução da biodiversidade terrestre",
        ],
    },
    {
        numb: 14,
        question: "Como as marés negras afetam o ambiente marinho?",
        answer: "Destruição de habitats e intoxicação da vida marinha",
        options: [
            "Destruição de habitats e intoxicação da vida marinha",
            "Redução da temperatura da água",
            "Aumento da oxigenação da água",
            "Melhoria da qualidade da água",
        ],
    },
    {
        numb: 15,
        question: "O que é a poluição por nutrientes?",
        answer: "Acúmulo excessivo de nutrientes como nitrogênio e fósforo",
        options: [
            "Acúmulo excessivo de nutrientes como nitrogênio e fósforo",
            "Contaminação com metais pesados",
            "Acúmulo de resíduos plásticos",
            "Derramamento de petróleo",
        ],
    },
    {
        numb: 16,
        question: "Qual é uma das consequências da poluição por pesticidas nos oceanos?",
        answer: "Diminuição da qualidade da água e efeitos nocivos em organismos marinhos",
        options: [
            "Diminuição da qualidade da água e efeitos nocivos em organismos marinhos",
            "Aumento da biodiversidade marinha",
            "Redução da salinidade da água",
            "Destruição de habitats terrestres",
        ],
    },
    {
        numb: 17,
        question: "Qual é um dos principais responsáveis pela poluição por nutrientes?",
        answer: "Esgoto agrícola e urbano",
        options: [
            "Esgoto agrícola e urbano",
            "Derramamento de petróleo",
            "Poluição térmica",
            "Descarte de plásticos",
        ],
    },
    {
        numb: 18,
        question: "Qual é a principal maneira de prevenir a poluição dos oceanos?",
        answer: "Implementar e seguir regulamentações ambientais rigorosas",
        options: [
            "Implementar e seguir regulamentações ambientais rigorosas",
            "Aumentar a produção industrial",
            "Reduzir a quantidade de áreas marinhas protegidas",
            "Utilizar mais produtos químicos",
        ],
    },
    {
        numb: 19,
        question: "O que são as correntes marinhas e como elas afetam a poluição dos oceanos?",
        answer: "São fluxos de água que podem transportar poluentes para diferentes áreas",
        options: [
            "São fluxos de água que podem transportar poluentes para diferentes áreas",
            "São áreas de alta concentração de nutrientes",
            "São zonas sem poluição",
            "São áreas com alta concentração de oxigênio",
        ],
    },
    {
        numb: 20,
        question: "Qual é o efeito das mudanças climáticas na poluição dos oceanos?",
        answer: "Intensificação de problemas existentes, como acidificação e eventos meteorológicos extremos",
        options: [
            "Intensificação de problemas existentes, como acidificação e eventos meteorológicos extremos",
            "Redução da poluição plástica",
            "Aumento da biodiversidade",
            "Melhoria da qualidade da água",
        ],
    },
];
