let questions = [
    // Poluição dos Oceanos
    {
        numb: 1,
        question: "Qual é a principal fonte de poluição plástica nos oceanos?",
        answer: "Descarte inadequado de plásticos",
        options: [
            "Derramamento de petróleo",
            "Esgoto industrial",
            "Descarte inadequado de plásticos",
            "Fertilizantes agrícolas",
        ],
    },
    {
        numb: 2,
        question: "Qual é uma forma eficaz de reduzir a poluição plástica nos oceanos?",
        answer: "Reduzir o uso de plásticos descartáveis",
        options: [
            "Reduzir o uso de plásticos descartáveis",
            "Aumentar a produção de plásticos recicláveis",
            "Desenvolver novos tipos de plásticos",
            "Queimar plásticos em alta temperatura",
        ],
    },
    {
        numb: 3,
        question: "Qual é o impacto da poluição por óleo nos oceanos?",
        answer: "Danos aos ecossistemas marinhos e morte de espécies aquáticas",
        options: [
            "Aumento da temperatura da água",
            "Danos aos ecossistemas marinhos e morte de espécies aquáticas",
            "Aumento da biodiversidade",
            "Redução do pH da água",
        ],
    },
    {
        numb: 4,
        question: "Qual é uma forma de evitar a poluição dos oceanos?",
        answer: "Reduzir o uso de plásticos descartáveis",
        options: [
            "Reduzir o uso de plásticos descartáveis",
            "Incentivar o uso excessivo de fertilizantes",
            "Construir mais portos industriais",
            "Expandir o turismo em áreas costeiras",
        ],
    },
    {
        numb: 5,
        question: "Qual é um exemplo de prática que não ajuda na proteção dos ecossistemas marinhos?",
        answer: "Expandir a pesca industrial sem regulamentação",
        options: [
            "Reduzir o descarte de resíduos plásticos no mar",
            "Proteger áreas marinhas e costeiras",
            "Expandir a pesca industrial sem regulamentação",
            "Restaurar habitats danificados",
        ],
    },
    {
        numb: 6,
        question: "Por que é importante controlar o despejo de resíduos no mar?",
        answer: "Para proteger a vida marinha e a qualidade da água",
        options: [
            "Para reduzir a quantidade de lixo nas praias",
            "Para proteger a vida marinha e a qualidade da água",
            "Para aumentar a poluição dos oceanos",
            "Para expandir as zonas industriais",
        ],
    },
    {
        numb: 7,
        question: "Qual é um benefício de manter a saúde dos ecossistemas marinhos?",
        answer: "Proteger a biodiversidade e melhorar a qualidade da água",
        options: [
            "Aumentar a poluição e a degradação",
            "Proteger a biodiversidade e melhorar a qualidade da água",
            "Expandir a construção em áreas costeiras",
            "Intensificar o turismo em zonas sensíveis",
        ],
    },
    {
        numb: 8,
        question: "Como o uso eficiente da água contribui para a mitigação da mudança climática?",
        answer: "Reduz a necessidade de tratamento e distribuição, economizando energia",
        options: [
            "Aumenta o consumo de água e a poluição",
            "Reduz a necessidade de tratamento e distribuição, economizando energia",
            "Facilita o desenvolvimento urbano sem controle",
            "Expande a agricultura intensiva",
        ],
    },
    {
        numb: 9,
        question: "Qual é o benefício da reutilização de águas residuais para a gestão sustentável?",
        answer: "Reduz a demanda sobre os recursos hídricos e diminui o impacto ambiental",
        options: [
            "Aumenta a poluição e o consumo de água",
            "Reduz a demanda sobre os recursos hídricos e diminui o impacto ambiental",
            "Facilita a expansão urbana sem regulamentação",
            "Destrói habitats naturais",
        ],
    },
    {
        numb: 10,
        question: "Por que é importante monitorar a qualidade da água para combater a mudança climática?",
        answer: "Ajuda a identificar e mitigar fontes de poluição e proteger os ecossistemas aquáticos",
        options: [
            "Aumenta a poluição e a degradação ambiental",
            "Ajuda a identificar e mitigar fontes de poluição e proteger os ecossistemas aquáticos",
            "Facilita a expansão industrial em áreas naturais",
            "Destrói habitats aquáticos",
        ],
    },
    {
        numb: 11,
        question: "Qual é o papel da educação pública na gestão sustentável da água para a mudança climática?",
        answer: "Melhora a conscientização e incentiva práticas de conservação e uso responsável da água",
        options: [
            "Aumenta o consumo e o desperdício de água",
            "Melhora a conscientização e incentiva práticas de conservação e uso responsável da água",
            "Facilita a poluição dos recursos hídricos",
            "Expande a construção em áreas naturais",
        ],
    },
    {
        numb: 12,
        question: "Por que é importante converter plásticos e outros resíduos sólidos encontrados nos rios em combustíveis alternativos?",
        answer: "Reduz a quantidade de resíduos plásticos em aterros e oceanos e pode gerar energia",
        options: [
            "Facilita o aumento da poluição dos oceanos",
            "Reduz a quantidade de resíduos plásticos em aterros e oceanos e pode gerar energia",
            "Facilita a expansão industrial sem controle",
            "Aumenta o desperdício de recursos naturais",
        ],
    },
    {
        numb: 13,
        question: "Como a utilização de resíduos de madeira e papel encontrados nos rios pode ajudar na geração de energia?",
        answer: "Pode ser convertida em biomassa para produção de energia térmica e elétrica",
        options: [
            "Aumenta a poluição do ar",
            "Pode ser convertida em biomassa para produção de energia térmica e elétrica",
            "Facilita a poluição dos oceanos",
            "Reduz a qualidade do solo",
        ],
    },
    {
        numb: 14,
        question: "Qual é uma das formas mais eficazes de economizar energia em casa?",
        answer: "Instalar lâmpadas de LED",
        options: [
            "Utilizar aparelhos elétricos de alto consumo",
            "Instalar lâmpadas de LED",
            "Manter luzes acesas o tempo todo",
            "Ligar e desligar os aparelhos constantemente",
        ],
    },
    {
        numb: 15,
        question: "Como a reciclagem contribui para a economia de energia?",
        answer: "Reduzindo a necessidade de produção de novos materiais",
        options: [
            "Aumentando o consumo de recursos naturais",
            "Reduzindo a necessidade de produção de novos materiais",
            "Aumentando a produção de energia",
            "Produzindo mais resíduos",
        ],
    },
    {
        numb: 16,
        question: "Qual é o impacto da reciclagem de plásticos na economia de energia?",
        answer: "Reduz a energia necessária para produzir novos plásticos",
        options: [
            "Aumenta o consumo de energia",
            "Reduz a energia necessária para produzir novos plásticos",
            "Diminui a durabilidade dos produtos",
            "Aumenta o desperdício",
        ],
    },
    {
        numb: 17,
        question: "Qual é uma maneira eficiente de economizar água em casa?",
        answer: "Reutilizar água da máquina de lavar para outras tarefas",
        options: [
            "Deixar a torneira aberta enquanto escova os dentes",
            "Reutilizar água da máquina de lavar para outras tarefas",
            "Tomar banhos mais longos",
            "Lavar o carro com mangueira aberta",
        ],
    },
    {
        numb: 18,
        question: "Qual prática contribui para a economia de água e energia ao mesmo tempo?",
        answer: "Usar a máquina de lavar em ciclos curtos e com a capacidade máxima",
        options: [
            "Lavar roupas com frequência e sem planejamento",
            "Usar a máquina de lavar em ciclos curtos e com a capacidade máxima",
            "Deixar torneiras gotejando",
            "Lavar pratos com água quente em grande quantidade",
        ],
    },
];
